
variable "compression_level" {
  type    = string
  default = "6"
}

variable "cpus" {
  type    = string
  default = "1"
}

variable "disk_size" {
  type    = string
  default = "40000"
}

variable "iso_checksum" {
  type    = string
  default = "1723cbbeb1aee26a54e1370b688e7dc03921402348d2a60086c58c18cd9cf24b"
}

variable "memory" {
  type    = string
  default = "1024"
}

variable "mirror" {
  type    = string
  default = "https://mirror.leaseweb.com/devuan"
}

variable "ssh_timeout" {
  type    = string
  default = "60m"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command           = ["<esc><wait>auto priority=critical preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/devuan-3/preseed.cfg <wait>", "passwd/root-password=${var.root_password} <wait>", "passwd/root-password-again=${var.root_password} <wait>", "passwd/user-fullname=${var.vagrant_username} <wait>", "passwd/username=${var.vagrant_username} <wait>", "passwd/user-password=${var.vagrant_password} <wait>", "passwd/user-password-again=${var.vagrant_password} <wait>", "keymap=us <wait>", "tasks=standard <wait>", "choose-init/select_init=sysvinit<wait>", "<enter><wait>"]
  boot_wait              = "5s"
  disk_size              = "${var.disk_size}"
  guest_os_type          = "Ubuntu_64"
  headless               = "true"
  http_directory         = "http"
  iso_checksum           = "${var.iso_checksum}"
  iso_url                = "${var.mirror}/devuan_beowulf/installer-iso/devuan_beowulf_3.1.1_amd64_netinstall.iso"
  output_directory       = "output-devuan-${var.version}-amd64-${build.type}"
  shutdown_command       = "sudo /sbin/shutdown -h now"
  ssh_handshake_attempts = "200"
  ssh_password           = "vagrant"
  ssh_timeout            = "${var.ssh_timeout}"
  ssh_username           = "vagrant"
  vboxmanage             = [["modifyvm", "{{ .Name }}", "--memory", "${var.memory}"], ["modifyvm", "{{ .Name }}", "--cpus", "${var.cpus}"]]
  vm_name                = "packer-devuan-3-amd64"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    scripts = ["scripts/ubuntu/apt.sh", "scripts/ubuntu/virtualbox.sh", "scripts/ubuntu/vmware.sh", "scripts/common/vagrant.sh", "scripts/common/sshd.sh", "scripts/ubuntu/cleanup.sh"]
  }

  post-processor "vagrant" {
    compression_level = "${var.compression_level}"
    output            = "devuan-3-amd64-<no value>.box"
  }
}
