---
name: packer
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  pre_build:

    # A job to see if the entrire jobs should be skipped.
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: same_content
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/*.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  packer:
    runs-on: macos-10.15
    needs:
      - pre_build
    if: ${{ (needs.pre_build.outputs.should_skip != 'true') || (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'schedule') }}
    strategy:
      matrix:
        box:
          - FreeBSD-13.0
          - FreeBSD-12.3
          - OpenBSD-7.1
          - OpenBSD-7.0
          - OpenBSD-6.9
          - Ubuntu-20.04
          - Devuan-3
          - Devuan-4
          - Debian-11
          - Fedora-35
          - Fedora-36
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Cache packer_cache
        uses: actions/cache@v2
        env:
          cache-name: packer_cache
        with:
          path: ${{ matrix.box }}/packer_cache
          key: packer_cache-${{ matrix.box }}-${{ hashFiles('${{ matrix.box }}/box.pkr.hcl') }}

      - name: Show vagrant version
        run: |
          Vagrant --version

      - name: Show VirtualBox version
        run: |
          virtualbox -h

      - name: Show packer version
        run: |
          packer --version

      - name: Validate HCL
        run: |
          (cd "${{ matrix.box }}" && packer validate -only virtualbox-iso.default box.pkr.hcl)

      - name: Build
        run: |
          bundle exec rake -C "${{ matrix.box }}"
          ( cd ${{ matrix.box }} && mv virtualbox.box ${{ matrix.box }}.box )

      - name: Upload ${{ matrix.box }}/${{ matrix.box }}.box
        uses: actions/upload-artifact@v2
        with:
          name: boxes
          path: ${{ matrix.box }}/${{ matrix.box }}.box

  create_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: |
          YYYYMMDD=`date "+%Y%m%d"`
          HHMM=`date "+%H%M"`
          echo "::set-output name=version::${YYYYMMDD}.${HHMM}"

  publish:

    # publish boxes when:
    #
    # * the workflow should not be skipped, and
    # * the event that triggered the workflow is push to branch 'main', i.e.
    #   merge into 'main' from a PR
    #
    # or when:
    # * the event that triggered the workflow is schedule, i.e. cron
    #
    # instead of using preprocessor in packer, upload all boxes when all
    # packer jobs succeed because matrix is used in packer job, and when a
    # job in the matrix is failed, other successful job uploads multiple
    # times.
    #
    # A secret, VAGRANT_CLOUD_TOKEN, must be created in the repository.
    runs-on: macos-10.15
    needs:
      - pre_build
      - packer
      - create_version
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'schedule') }}
    steps:

      - name: Download boxes
        uses: actions/download-artifact@v2
        with:
          name: boxes

      - name: Publish boxes to vagrant cloud
        run: |
          export VAGRANT_CLOUD_TOKEN=${{ secrets.VAGRANT_CLOUD_TOKEN }}
          VERSION=${{ needs.create_version.outputs.version }}

          ls -al
          # e.g. FreeBSD-12.3.box FreeBSD-13.0.box ...
          BOXES=`/bin/echo *-*.box`

          for BOX in ${BOXES}; do

            # e.g. freebsd-12.3
            NAME=`echo ${BOX} | tr "[:upper:]" "[:lower:]" | sed -e 's/.box//'`
            Vagrant cloud publish --force --release "trombik/ansible-${NAME}-amd64" "${VERSION}" virtualbox "${BOX}"
          done

  release:

    # create release, upload the box files to the release page.
    #
    # vagrant cloud has a rather strict rate limit. when CI in roles downloads
    # a box, the CI caches the box file. however, the files are cached only
    # when successful at the end of the CI. if you keep fixing, vagrant cloud
    # eventually returns HTTP 429 status code. workaround the issue by
    # uploading box files to the release page on GitHub.
    #
    # see:
    # https://www.vagrantup.com/vagrant-cloud/request-limits
    runs-on: ubuntu-latest
    needs:
      - pre_build
      - packer
      - create_version
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'schedule') }}
    steps:

      - name: Download boxes
        uses: actions/download-artifact@v2
        with:
          name: boxes

      - name: Rename box files
        run: |
          ls -al

          # e.g. FreeBSD-12.3.box FreeBSD-13.0.box ...
          BOXES=`/bin/echo *-*.box`

          for BOX in ${BOXES}; do

            # e.g. freebsd-12.3
            NAME=`echo ${BOX} | tr "[:upper:]" "[:lower:]" | sed -e 's/.box//'`

            MACHINE="amd64"
            if echo "${NAME}" | grep -q "centos"; then
              MACHINE="x86_64"
            fi

            # e.g. ansible-freebsd-12.3-amd64.box
            mv ${BOX} ansible-${NAME}-${MACHINE}.box
          done

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create_version.outputs.version }}
          artifacts: "*.box"
