---
name: packer
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  pre_build:

    # A job to see if the entrire jobs should be skipped.
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: same_content
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/*.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  packer:
    runs-on: macos-10.15
    needs:
      - pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        box:
          - FreeBSD-13.0
          - FreeBSD-12.3
          - OpenBSD-7.0
          - OpenBSD-6.9
          - Ubuntu-20.04
          - Devuan-3
          - Devuan-4
          - Fedora-35
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Cache packer_cache
        uses: actions/cache@v2
        env:
          cache-name: packer_cache
        with:
          path: ${{ matrix.box }}/packer_cache
          key: packer_cache-${{ matrix.box }}

      - name: Show vagrant version
        run: |
          Vagrant --version

      - name: Show VirtualBox version
        run: |
          virtualbox -h

      - name: Show packer version
        run: |
          packer --version

      - name: Validate HCL
        run: |
          (cd "${{ matrix.box }}" && packer validate -only virtualbox-iso.default box.pkr.hcl)

      - name: Build
        run: |
          bundle exec rake -C "${{ matrix.box }}"
          ( cd ${{ matrix.box }} && mv virtualbox.box ${{ matrix.box }}.box )

      - name: Upload ${{ matrix.box }}/${{ matrix.box }}.box
        uses: actions/upload-artifact@v2
        with:
          name: boxes
          path: ${{ matrix.box }}/${{ matrix.box }}.box

  publish:

    # publish boxes to vagrant cloud.
    #
    # instead of using preprocessor in packer, upload all boxes when all
    # packer jobs succeed because matrix is used in packer job, and when a
    # job in the matrix is failed, other successful job uploads multiple
    # times.
    #
    # A secret, VAGRANT_CLOUD_TOKEN, must be created in the repository.
    runs-on: macos-10.15
    needs:
      - pre_build
      - packer
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    steps:

      - name: Download boxes
        uses: actions/download-artifact@v2
        with:
          name: boxes

      - name: Publish boxes
        run: |
          export VAGRANT_CLOUD_TOKEN=${{ secrets.VAGRANT_CLOUD_TOKEN }}
          YYYYMMDD=`date "+%Y%m%d"`
          HHMM=`date "+%H%M"`

          ls -al
          # e.g. FreeBSD-12.3.box FreeBSD-13.0.box ...
          BOXES=`/bin/echo *-*.box`

          for BOX in ${BOXES}; do

            # e.g. freebsd-12.3
            NAME=`echo ${BOX} | tr "[:upper:]" "[:lower:]" | sed -e 's/.box//'`
            Vagrant cloud publish --force --release "trombik/ansible-${NAME}-amd64" "${YYYYMMDD}.${HHMM}" virtualbox "${BOX}"
          done
