---
name: yamllint
on:
  - pull_request
  - push
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Install python
        uses: actions/setup-python@v4.3.1

      - name: Install dependencies
        run: |
          sudo apt-get install \
            yamllint

      - name: Run yamllint
        run: |
          yamllint -c .yamllint.yml .
